### ISSUE TITLE
Not in marketplace

### ISSUE THREAD

**Issue by Ina-Ravioli** [jeroentvb/spicetify-playlist-icons#12]
I used to have it installed in marketplace today, but I just opened Spotify today, and it's not in marketplace or installed.

**Comment by jeroentvb** [comment]
This was an issue where github didn't return this repo in the search results for repo's with the `spicetify-extensions` tag. It seems to be back for me now. Can you confirm this?

**Comment by jeroentvb** [comment]
It's included in github's search results again.
