### ISSUE TITLE
Icons showing up twice

### ISSUE THREAD

**Issue by Meiloorun** [jeroentvb/spicetify-playlist-icons#13]
For some reason, with the extension installed, my playlist icons show up twice.

![image](https://user-images.githubusercontent.com/49651674/198998375-9b41d119-21de-45de-b852-a9c8d6c5d720.png)

When removing the extension, the icons do not show at all, so it isn't another extension or theme that is showing the other icon.

**Comment by jeroentvb** [comment]
This isn't happening for me (windows 10, spicetify 2.14.1, spotify 1.1.97).

Can you provide reproduction steps, or maybe look for errors in the console?

**Comment by Meiloorun** [comment]
Windows 10, Spicetify 2.14.1, SpotX 1.6, Spotify 1.1.97.962 

I don't see any console errors. 

I simply installed the extension through the Spicetify Marketplace and found there to be 2 icons.

Do you think it could be SpotX? I don't think that's the case, because it doesn't show any icons on a normal SpotX install.

**Comment by jeroentvb** [comment]
I think it might be a marketplace issue. Could you try resetting the marketplace in the marketplace settings, and making sure you've got the latest marketplace version?

**Comment by jeroentvb** [comment]
Are you still having this issue? @Meiloorun

**Comment by Meiloorun** [comment]
> Are you still having this issue? @Meiloorun 

It was definitely the store issue, I had recently reinstalled the store anyways but I was still getting duplicates, so I just got it from here instead and the duplicates were gone
