### ISSUE TITLE
weird glitch around playlist sound indicator

### ISSUE THREAD

**Issue by vathanac** [jeroentvb/spicetify-playlist-icons#14]
Comfy theme

![image](https://user-images.githubusercontent.com/87689818/207320290-04fe2dbb-387d-4c4d-aedd-bd2182616e51.png)

**Comment by jeroentvb** [comment]
This is an issue with comfy, as playlist-icons does not alter the now playing icon. Even with small playlist icons the now playing icon doesn't take up full height, so if you apply a background (which comfy apparently does), it won't fill.
