### ISSUE TITLE
[Feature Request] Add Playlist Icons in Add to Playlist Context Menu

### ISSUE THREAD

**Issue by Satanarious** [jeroentvb/spicetify-playlist-icons#15]
It would be a great addition if we were able to see the playlist icon in the add to playlist context menu in the place as shown in the image below with red dots.

![image](https://user-images.githubusercontent.com/42642682/224308484-96b82517-28ce-4454-a38e-499792799203.png)

It would be easier to identify playlists with their icon.

**Comment by jeroentvb** [comment]
Great suggestion. I'll see what I can do.
