### ISSUE TITLE
Not Working Anymore For Me after last update

### ISSUE THREAD

**Issue by JSandhu03** [jeroentvb/spicetify-playlist-icons#18]
Hi, so I know this is probably an isolated issue as I'm on a fairly older version of spotify but before yesterday's update, everything was workign fine. But after the update, the extension has stopped to work for me. I was just wondering if you could provide me with the older .js file prior to yesterday's update if that's possible. 
Thanks

**Comment by jeroentvb** [comment]
Should still work with the current version. See https://github.com/jeroentvb/spicetify-playlist-icons/issues/17
