### ISSUE TITLE
Its laggy and rerendering playlist while scrolling. not smooth

### ISSUE THREAD

**Issue by Tetrax-10** [jeroentvb/spicetify-playlist-icons#2]
https://user-images.githubusercontent.com/75513645/170172074-68a59873-2e4c-4d5e-9ec9-bf63b74ccdff.mp4

**Comment by jeroentvb** [comment]
This was an issue present in the first version, which had to do with the size of the playlist list container size and the way spotify handles the playlist list element (they remove items from the dom when scrolling out of view).

I'm not sure why it's happening for you, cause it works smoothly for me and I'm not able to reproduce it. But I'm still on spotify 1.1.84 with spicetify 2.9.8.

What os/spotify/spicetify version are you using?

**Comment by jeroentvb** [comment]
While checking out #3, I noticed that behaviour only with the big icons. This has to do with the big icons making the playlist container bigger than spotify wants it to be. Unfortunately, due to the way the sizing of the playlist container is handled, I'm unable to do anything about it.
