### ISSUE TITLE
[Bug]: Won't refresh icons in a playlist, if you remove a song from another playlist it appears in.

### ISSUE THREAD

**Issue by kaboomtrap** [jeroentvb/spicetify-playlist-icons#21]
To reproduce: 
1. Create Playlist One.
2. In Playlist One, add song(s) from an existing playlist (Playlist Two).
3. In Playlist Two, check if the icons from the new playlist show up here (they do).
4. In Playlist One, remove some of the songs you added.
5. Go back to Playlist Two. It didn't update the playlist icons next to the songs which are removed from Playlist One.

Restarting the app didn't refresh the icons. The icons finally refresh after editing Playlist One's name.
If this isn't reproduceable, the extension is probably clashing with something else I have installed...

### ℹ Environment / Computer Info
```Markdown
Spotify for Windows (64 bit)
1.2.33.1042.g26c92729
Spicetify v2.35.1
Theme: marketplace
Extensions: bookmark.js, keyboardShortcut.js, allOfArtist.js, playbarClock.js, tracksToEdges.js, extended-copy.js, romaji-convert.js, playlist-icons.js, PlaylistProxy.js, spicetify-playlist-labels.js, dist\search-on-youtube\prism.mjs, section-marker.js, resume-playlist.js, spicetify-private-session.js, LuckyLP.js, spicetify-furigana-lyrics.js, pip.js, QueueTime.js, CoverAmbience.js, upcomingSong.js, AnonymizedRadios.js, songstats.js, wikify.js, adblock.js, utilities.js, who-added.js, imageOpener.js, playOnYouTube.js, addToQueueTop.js, lastfm.js, css-editor.js, removeFriendsActivity.js, playing-source.js, djinfo.js, autoSkipWrapper.js
Custom apps: marketplace
```

**Comment by jeroentvb** [comment]
Are you talking about the playlist icons in the left hand sidebar, or the 'add to playlist' contextmenu? The latter doesn't seem to even render playlist icons for me. As for the former, I can't test that, as they are only shown in legacy mode on old spotify versions.

**Comment by kaboomtrap** [comment]
Sorry for completely confusing you, I wrote about a different extension! You may close and delete this issue. Let me make up for it and open up a separate issue I encountered with [spicetify-playlist-icons](https://github.com/jeroentvb/spicetify-playlist-icons).
