### ISSUE TITLE
Broken on update

### ISSUE THREAD

**Issue by updxg** [jeroentvb/spicetify-playlist-icons#7]
The extension seems broken on my end for a few updates already. A Spotify update probably broke the .js execution. I'm unsure on how I could debug further as the only thing I could catch on was the .js failing to create any html element in the sidebar.

- **Spotify ver.:** 1.1.91.824
- **Spicetify ver.:** v2.11.2
- **Marketplace ver.:** v0.7.1 _(happened on v0.7.0 too, probably redundant info)_
- **OS:** Windows 10

**Comment by jeroentvb** [comment]
I am unable to reproduce the issue. Using the same versions as you are, except spicetify, cause 2.11.2 doesn't exist (using 2.11.1).

Could you share a screenshot of your console log?

**Comment by updxg** [comment]
My bad, it was a typo I didn't bother proof-reading for.

I saved a [.log file](https://github.com/jeroentvb/spicetify-playlist-icons/files/9262331/xpui.app.spotify.com-1659637805438.log) of:
1. Downloading the extension
2. Pressing reload now
3. Standing by on the marketplace screen after reloading

[Screenshot](https://user-images.githubusercontent.com/94653983/182963083-85e15fce-425d-4659-90f8-2e3ac5f1a310.png)

**Comment by jeroentvb** [comment]
I don't see any playlist icons related issue in the log.

One thing you could try is manually installing playlist icons and see if that works. This rules out if it's a marketplace issue. Installation instructions [here](https://github.com/jeroentvb/spicetify-playlist-icons/tree/dist#installation).
Dist file [here](https://github.com/jeroentvb/spicetify-playlist-icons/blob/dist/playlist-icons.js).

**Comment by updxg** [comment]
I've done so, to the same result.

But, in doing all that, I have opened the config-xpui.ini to check if the .js is there, only to find that the sidebar_config is set to 0 since the playlist-icons managed to break my sidebar a few Spotify updates ago (it made it so the sidebar scrolled past all the playlists into nothing) and I guess I forgot all about that.

Thank you for helping me rectify the problem, and sorry for the troubles :)
